//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Advertisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisement()
        {
            this.Visits = new HashSet<Visit>();
        }
        public int AdvertisementId { get; set; }
        public int TypeAdvertisement { get; set; }
        public int Representative { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Group { get; set; }
        public int Moderation { get; set; }

        [JsonIgnore]
        public virtual Area Area1 { get; set; }
        [JsonIgnore]
        public virtual Group Group1 { get; set; }
        [JsonIgnore]
        public virtual TypeAdvertisement TypeAdvertisement1 { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
