//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Area()
        {
            this.Advertisements = new HashSet<Advertisement>();
        }

        public int AreaId { get; set; }
        public string Name { get; set; }
        public int Representative { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string DescriptionGroups { get; set; }
        public byte[] PhotoLogo { get; set; }
        public byte[] Photo1 { get; set; }
        public byte[] Photo2 { get; set; }
        public byte[] Photo3 { get; set; }
        public byte[] Photo4 { get; set; }
        public byte[] Photo5 { get; set; }
        public byte[] Photo6 { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public int Capacity { get; set; }
        public string Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Advertisement> Advertisements { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
    }
}
