//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorisationHistory
    {
        public int id { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public bool State { get; set; }
    
        public virtual User User { get; set; }
    }
}
