//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Advertisements = new HashSet<Advertisement>();
        }
        public int BandId { get; set; }
        public string Name { get; set; }
        public int Producer { get; set; }
        public string Description { get; set; }
        public string DescriptionAreas { get; set; }
        public byte[] PhotoLogo { get; set; }
        public byte[] Photo1 { get; set; }
        public byte[] Photo2 { get; set; }
        public byte[] Photo3 { get; set; }
        public byte[] Photo4 { get; set; }
        public byte[] Photo5 { get; set; }
        public byte[] Photo6 { get; set; }
        public string SpotifyLink { get; set; }
        public string AppleMusicLink { get; set; }
        public string DeezerLink { get; set; }
        public string YandexMusicLink { get; set; }
        public string YouTubeMusicLink { get; set; }
        public string YouTubeLink { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public int Genre { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Advertisement> Advertisements { get; set; }
        [JsonIgnore]
        public virtual Genre Genre1 { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
    }
}
