//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Visit
    {
        public int VisitId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int Device { get; set; }
        public int Advertisiment { get; set; }
        [JsonIgnore]
        public virtual Advertisement Advertisement { get; set; }
        [JsonIgnore]
        public virtual TypeDevice TypeDevice { get; set; }
    }
}
